name: Workflow for Codecov
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install python dependencies
        run: pip install -r src/python/requirements.txt

      - name: Run tests and collect coverage
        run: |
          python -m pytest src/python/katas/*/*.py --cov=src/python
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
